name: slack - GitHub Actions Slack integration
on:
  push:
    branches:
    - 'main'
jobs:
  job_1:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: act10ns/slack@v2.1.0
      with:
        status: starting
        channel: '#apr24_bds_int_plant_recognition'
        message: |
          Author: ${{ github.actor }}
          Message: ${{ github.event.head_commit.message }}
          See the changes here: ${{ github.repository }}
      if: always()
    - name: Checkout
      uses: actions/checkout@v4
    - name: Dummy command
      run: |
        ls -lart
    - uses: act10ns/slack@v2.1.0
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#apr24_bds_int_plant_recognition'
      if: always()
